# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# sudo: false is removed

language: R
warnings_are_errors: true
cache: packages
r: release

os:
  - linux
  - osx

env:
  global: RGL_USE_NULL=TRUE

r_check_args: "--as-cran --install-args=--build"

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install libmpfr-dev libxml2-dev libcgal-dev libglu1-mesa-dev mesa-common-dev; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; 
      then 
        sudo apt-get update -qq ;
        sudo apt-get install -y libmng2 ; 
        sudo apt-get install -y libmng1 ; 
        sudo updatedb;
    fi
